### ISSUE TITLE
Add support for partial content request

### ISSUE THREAD

**Issue by artoale** [grow/pygrow#129] opened 2015-09-17 11:44 UTC
As explained in [this](http://stackoverflow.com/questions/8088364/html5-video-will-not-loop) SO, video seeking/looping doesn't work in chrome if partial content request is not supported by the server serving the video.

When using looped videos, I got this error in the logs:
```
Traceback (most recent call last):
  File "/Users/aartoni/homebrew/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/wsgiref/handlers.py", line 86, in run
    self.finish_response()
  File "/Users/aartoni/homebrew/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/wsgiref/handlers.py", line 128, in finish_response
    self.write(data)
  File "/Users/aartoni/homebrew/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/wsgiref/handlers.py", line 217, in write
    self._write(data)
  File "/Users/aartoni/homebrew/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 328, in write
    self.flush()
  File "/Users/aartoni/homebrew/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
```

Any chance of implement this at some point? 

Thanks

**Comment by jeremydw** [comment] 2015-09-19 00:49
Yep! We've already identified this issue, so marking this as a duplicate of #60. Hope to have a fix out soon.

**Closed by jeremydw** 2015-09-19 00:49 UTC

**Comment by artoale** [comment] 2015-09-19 00:50
Sorry for not spotting the previous issue - thanks!
