### ISSUE TITLE
Failure to update Grow

### ISSUE THREAD

**Issue by anonymousandrew** [grow/pygrow#136] opened 2015-09-30 21:36 UTC
$ curl https://install.growsdk.org | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   377  100   377    0     0    732      0 --:--:-- --:--:-- --:--:--   732
Traceback (most recent call last):
  File "/var/folders/00/1j02r000h01000cxqpysvccm00640b/T/tmp.XXXXXXXXXX.tMv7cedd/install_growsdk.py", line 169, in <module>
    main()
  File "/var/folders/00/1j02r000h01000cxqpysvccm00640b/T/tmp.XXXXXXXXXX.tMv7cedd/install_growsdk.py", line 165, in main
    install(rc_path=args.rc_path, bin_path=args.bin_path, force=args.force)
  File "/var/folders/00/1j02r000h01000cxqpysvccm00640b/T/tmp.XXXXXXXXXX.tMv7cedd/install_growsdk.py", line 69, in install
    release = json.loads(urllib.urlopen(RELEASES_API).read())[0]
KeyError: 0

**Comment by jeremydw** [comment] 2015-09-30 21:37
I think this has got to be a network connectivity issue between your machine and GitHub. That's both how the update check works and where the installer downloads the release from...

**Comment by jeremydw** [comment] 2015-10-12 22:22
Marking this as a dupe of #143

**Closed by jeremydw** 2015-10-12 22:22 UTC
