### ISSUE TITLE
Add coffescript support

### ISSUE THREAD

**Issue by jet9** [grow/pygrow#71] opened 2015-05-11 15:17 UTC
Grow ideally useful for SPA. It should be good idea to add coffeescript support to grow sdk as one of built-in preprocessors (like SASS support, for example).

**Comment by fotinakis** [comment] 2015-05-11 16:09
Or how about an ES2015 transpiler instead? :)

**Comment by jet9** [comment] 2015-05-11 16:24
@fotinakis  Why "instead"? Why not "along with"? 

Plz provide me with good documentation or example for creating preprocessors and I'll send you pull request for topic.

**Comment by jeremydw** [comment] 2015-05-11 19:31
After using Grow on several projects with various levels of frontend complexity, I'm actually recommending to use Gulp for preprocessors outside of what Grow comes with builtin, and am considering deprecating the Closure Compiler and Sass preprocessors in favor of internal-only preprocessors such as those for data retrieval (Google Spreadsheets) or translation compilation.

Why? Gulp just does a pretty darn good job at preprocessing, and I see little need to reproduce it inside Grow. Specifically, here's an example: we had a project where we needed to Sass compile something, then autoprefix it, then concatenate two dependencies to the front of the file, and then build the result to the `static` directory. While you can do 3/4 things with the Closure Compiler, it's slow and there's no builtin for autoprefixer. Gulp made this pretty trivial and didn't require us to build anything special.

So, what do you think? Can we say "to use CoffeScript on Grow projects, use Gulp"? I'll be assessing the current preprocessors soon, seeing if we should deprecate Closure Compiler (to start), writing up some more docs on using Gulp, and adding some themes with built-in `package.json`, `bower.json`, and `gulpfile.js` files.

**Comment by jet9** [comment] 2015-05-11 21:20
Gulp looks so brilliant for preprocessor tasks. But live reload feature is extremely used in my grow projects. In connection Gulp + Grow which of two will maintain livereload?  
As I understand from Gulp docs - each plugin is atomic action that can be used in stream processing. In this case should we use some plugin that will process file(s) within GrowSDK's workflow or just run shell commands like `grow build`?
Or we should use Gulp as a external preprocessing subsystem for Grow? Have you any Grow examples for this case?

**Comment by jeremydw** [comment] 2015-05-11 21:26
For maintaining live reload, I use a `watch` task with Gulp for any preprocessed static files (such as CSS or JS files preprocessed by the Sass or Closure Compiler). I set the default task in Gulp to `watch`, and then execute my development server with:

```gulp & grow run```

This causes the default task in Gulp (`watch`) to run, and spins up the local development server for Grow. Pressing `Ctrl C` stops them both, which is exactly what you want.

To answer your second question, I use Gulp to preprocess files into a static directory that Grow can pick files up from (in Grow's podspec language, it would be a `static_dir`). Then, `grow build` incorporates static files generated by Gulp.

To build a Grow site that leverages Gulp, I would add a Gulp task `build` that runs all the preprocessors, and then run:

```gulp build && grow build```

The first command runs the Gulp preprocessors, and the second command generates the exported fileset from Grow. It works really well for me.

Yes, I think I owe you (and others) some examples. :) Some of the projects I've worked on that leverage this workflow are sadly not open source, but I will go ahead and add an example that leverages gulp and bower to preprocess assets for Grow, along with build commands. I'll add it to the https://github.com/growthemes project, so you'd be able to run `grow init scaffold-gulp` to get a simple gulp-powered Grow site running.

What do you think?

**Comment by jet9** [comment] 2015-05-11 21:40
Sounds good... and easy )))

If I need to implement Gulp in existing project I should split workflow in two stages: 1. Gulp watch-loop-preprocessing and 2. Grow live-reload (by removing all preprocessors from `podspec.yaml`). And run it consequenty `gulp & grow run .`. If I loose nothing this approach is more powerful than built-in preprocessing and really easy to implement. 

Thanks a lot for a good idea!

**Comment by jeremydw** [comment] 2015-05-11 22:11
That's exactly right – it's basically as easy to maintain (although, sure, you'll need to install Gulp beforehand – which is something you wouldn't need to do with the builtins) – but it's way more powerful and flexible long-term since you can leverage all of Gulp's modules and its piping functionality.

Don't forget to run `gulp build` before any action that leverages a grow build. For example, `gulp build && grow deploy` to deploy.

I'll go ahead and add an additional theme with documentation to illustrate how this process works and make it easy to set up, then I'll close this issue.

**Comment by jeremydw** [comment] 2015-07-25 17:44
Going to close out this old issue now. Note that since the filing of this issue we've updated the `scaffold` theme with an example `gulpfile`, making it easy to incorporate CoffeeScript into your project.

Here's the theme:
https://github.com/growthemes/scaffold

Which can be used with:

```
grow init scaffold
```

**Closed by jeremydw** 2015-07-25 17:44 UTC
